[package]
name = "backoff-futures"
version = "0.1.0"

authors = ["Jakub Wieczorek <jakub.adam.wieczorek@gmail.com>"]
keywords = ["backoff", "exponential", "futures"]
license = "MIT"
repository = "https://github.com/jakubadamw/backoff-futures"

edition = "2018"

[badges]
azure-devops = { project = "jakubadamw", pipeline = "github", build = "3" }

[dependencies]
backoff = "0.1"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
tokio-timer = { git = "https://github.com/tokio-rs/tokio" }

[dev-dependencies]
matches = "0.1"
