name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [beta, stable, nightly]

    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      run: rustup default $TOOLCHAIN
      env:
        TOOLCHAIN: ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      if: matrix.toolchain == 'nightly'
    - name: Install Clippy
      run: rustup component add clippy
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic
